In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

reviews = pd.read_csv(
    "../data/processed/reviews_cleaned.csv"
)

activities = pd.read_csv(
    "../data/processed/activities_cleaned.csv"
)

accommodation = pd.read_csv(
    "../data/processed/accommodation_cleaned.csv"
)

water_sports = pd.read_csv(
    "../data/processed/water_sports_cleaned.csv"
)

In [2]:
destination_master = (
    reviews
    .groupby(["Location_Name", "Located_City", "Location_Type"])
    .agg(
        Average_Rating=("Rating", "mean"),
        Review_Count=("Rating", "count")
    )
    .reset_index()
)

In [3]:
destination_master.head()

,Location_Name,Located_City,Location_Type,Average_Rating,Review_Count
0,Abhayagiri Dagaba,Anuradhapura,Religious Sites,4.302083,96
1,Ambewela Farms,Nuwara Eliya,Farms,3.897059,136
2,Ariyapala Mask Museum,Ambalangoda,Museums,3.870130,77
3,Arugam Bay,Arugam Bay,Beaches,4.058824,187
4,Baker's Falls,Nuwara Eliya,Waterfalls,3.959459,74

In [4]:
destination_master["Average_Rating"] = (
    destination_master["Average_Rating"].round(2)
)

In [5]:
most_common_month = (
    reviews.groupby("Location_Name")["Travel_Month"]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
    .reset_index()
)

most_common_month.columns = [
    "Location_Name",
    "Most_Common_Travel_Month"
]

In [6]:
destination_master = destination_master.merge(
    most_common_month,
    on="Location_Name",
    how="left"
)

In [7]:
print("Number of destinations:", destination_master["Location_Name"].nunique())

print("\nShape:", destination_master.shape)

destination_master.head(10)

Number of destinations: 76

Shape: (76, 6)

,Location_Name,Located_City,Location_Type,Average_Rating,Review_Count,Most_Common_Travel_Month
0,Abhayagiri Dagaba,Anuradhapura,Religious Sites,4.30,96,2
1,Ambewela Farms,Nuwara Eliya,Farms,3.90,136,1
2,Ariyapala Mask Museum,Ambalangoda,Museums,3.87,77,2
3,Arugam Bay,Arugam Bay,Beaches,4.06,187,7
4,Baker's Falls,Nuwara Eliya,Waterfalls,3.96,74,3
5,Bentota Beach,Bentota,Beaches,4.59,233,1
6,Bluefield Tea Gardens,Nuwara Eliya,Farms,4.22,314,1
7,Brief Garden - Bevis Bawa,Beruwala,Gardens,4.28,292,2
8,Bundala National Park,Weligatta,National Parks,4.70,189,2
9,Ceylon Tea Museum,Kandy,Museums,4.08,305,2

In [8]:
destination_master.isnull().sum()

Location_Name               0
Located_City                0
Location_Type               0
Average_Rating              0
Review_Count                0
Most_Common_Travel_Month    0
dtype: int64

In [9]:
destination_master.to_csv(
    "../data/processed/destination_master.csv",
    index=False,
    encoding="utf-8-sig"
)

In [10]:
destination_master.to_csv(
    "../data/processed/destination_master.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Destination master dataset saved successfully.")

Destination master dataset saved successfully.

In [11]:
destination_cities = (
    destination_master["Located_City"]
    .value_counts()
)

print(destination_cities)

Located_City
Nuwara Eliya     11
Anuradhapura     10
Kandy             6
Colombo           5
Sigiriya          3
Galle             3
Habarana          3
Nilaveli          2
Trincomalee       2
Haputale          2
Ella              2
Jaffna            2
Hikkaduwa         2
Ambalangoda       1
Arugam Bay        1
Beruwala          1
Katukitula        1
Bentota           1
Weligatta         1
Koslanda          1
Kalametiya        1
Unawatuna         1
Ahangama          1
Kalutara          1
Ampara            1
Mirissa           1
Negombo           1
Kalkudah          1
Pinnawala         1
Polonnaruwa       1
Pussellawa        1
Peradeniya        1
Deniyaya          1
Tissamaharama     1
Embilipitiya      1
Saliyapura        1
Name: count, dtype: int64

In [12]:
activity_districts = (
    activities["District"]
    .value_counts()
)

print(activity_districts)

District
Colombo         939
Gampaha         175
Kandy            70
Galle            64
Matale           45
Kalutara         43
Kegalle          35
Puttalam         29
Kurunegala       25
Ampara           15
Matara           13
Jaffna           11
Batticaloa       11
Ratnapura         8
Trincomalee       7
Anuradhapura      6
Hambantota        6
Nuwara Eliya      5
Polonnaruwa       5
Moneragala        4
Mullaitivu        3
Badulla           2
Kilinochchi       1
UNKNOWN           1
Name: count, dtype: int64

In [13]:
print("Destination cities:")
print(sorted(destination_master["Located_City"].dropna().unique()))

print("\nActivity districts:")
print(sorted(activities["District"].dropna().unique()))

Destination cities:
['Ahangama', 'Ambalangoda', 'Ampara', 'Anuradhapura', 'Arugam Bay', 'Bentota', 'Beruwala', 'Colombo', 'Deniyaya', 'Ella', 'Embilipitiya', 'Galle', 'Habarana', 'Haputale', 'Hikkaduwa', 'Jaffna', 'Kalametiya', 'Kalkudah', 'Kalutara', 'Kandy', 'Katukitula', 'Koslanda', 'Mirissa', 'Negombo', 'Nilaveli', 'Nuwara Eliya', 'Peradeniya', 'Pinnawala', 'Polonnaruwa', 'Pussellawa', 'Saliyapura', 'Sigiriya', 'Tissamaharama', 'Trincomalee', 'Unawatuna', 'Weligatta']

Activity districts:
['Ampara', 'Anuradhapura', 'Badulla', 'Batticaloa', 'Colombo', 'Galle', 'Gampaha', 'Hambantota', 'Jaffna', 'Kalutara', 'Kandy', 'Kegalle', 'Kilinochchi', 'Kurunegala', 'Matale', 'Matara', 'Moneragala', 'Mullaitivu', 'Nuwara Eliya', 'Polonnaruwa', 'Puttalam', 'Ratnapura', 'Trincomalee', 'UNKNOWN']